name: boutix
description: BOUTIX PRO - Gestion boutique & caisse style BIOS/DOS
publish_to: 'none'
version: 1.0.9+9

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.19.0
  printing: ^5.13.2
  pdf: ^3.11.1
  window_manager: ^0.4.3
  crypto: ^3.0.6
  file_picker: ^8.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
